from __future__ import annotations

import base64
import hashlib
import io
import json
import re
import zipfile
from datetime import datetime, timezone
from typing import Any

GENERATOR_VERSION = "eve-discovery-mt5-generator-v1"


def canonical(value: Any) -> str:
    return json.dumps(value, sort_keys=True, separators=(",", ":"), default=str)


def sha256_text(value: str) -> str:
    return hashlib.sha256(value.encode("utf-8")).hexdigest()


def safe_name(value: str, fallback: str = "EVE_Discovery") -> str:
    cleaned = re.sub(r"[^A-Za-z0-9_]+", "_", str(value or "")).strip("_")
    cleaned = re.sub(r"_+", "_", cleaned) or fallback
    if cleaned[0].isdigit():
        cleaned = f"EVE_{cleaned}"
    return cleaned[:80]


def mql_string(value: Any) -> str:
    return str(value).replace("\\", "\\\\").replace('"', '\\"')


def _or_int(field: str, values: list[int]) -> str:
    if not values:
        return "true"
    return "(" + " || ".join(f"{field} == {int(v)}" for v in values) + ")"


def _or_string(field: str, values: list[str]) -> str:
    if not values:
        return "true"
    return "(" + " || ".join(f'{field} == "{mql_string(v)}"' for v in values) + ")"


def source_expression(rules: dict[str, Any]) -> str:
    schedule = dict(rules.get("schedule") or {})
    environment = dict(rules.get("environment") or {})
    family = str(rules.get("family") or "momentum_continuation")
    expressions = [
        _or_int("f.weekday", [int(v) for v in schedule.get("weekdays") or []]),
        _or_int("f.month", [int(v) for v in schedule.get("months") or []]),
        _or_int("f.hour_utc", [int(v) for v in schedule.get("hours_utc") or []]),
        _or_string("f.session", [str(v) for v in schedule.get("sessions") or []]),
    ]

    regimes = [str(v) for v in environment.get("regimes") or []]
    expressions.append(_or_string("f.regime", regimes))
    for key, field in (("trend_12", "f.trend_12_band"), ("trend_48", "f.trend_48_band")):
        required = str(environment.get(key) or "any")
        if required == "directional":
            expressions.append(f'{field} != "flat"')
        elif required != "any":
            expressions.append(f'{field} == "{mql_string(required)}"')
    compression = str(environment.get("compression") or "any")
    if compression != "any":
        expressions.append(f'f.compression_band == "{mql_string(compression)}"')
    min_alignment = int(float(environment.get("min_alignment_abs") or 0))
    if min_alignment:
        expressions.append(f"MathAbs(f.alignment_score) >= {min_alignment}")
    alignment_sign = str(environment.get("alignment_sign") or "any")
    if alignment_sign == "up":
        expressions.append("f.alignment_score > 0")
    elif alignment_sign == "down":
        expressions.append("f.alignment_score < 0")

    family_expr = {
        "momentum_continuation": "f.direction != 0 && SignDouble(f.trend_12_atr) != 0 && f.direction == SignDouble(f.trend_12_atr) && MathAbs(f.return_3_pct) > 0.005",
        "alignment_continuation": f"f.alignment_score != 0 && MathAbs(f.alignment_score) >= {max(1, min_alignment)}",
        "pullback_continuation": "SignDouble(f.trend_12_atr) != 0 && f.direction == -SignDouble(f.trend_12_atr)",
        "volatility_breakout": "f.direction != 0 && MathAbs(f.return_1_pct) > MathAbs(f.return_3_pct)/4.0",
        "mean_reversion": "f.direction != 0 && (f.close_location <= 0.20 || f.close_location >= 0.80)",
        "candle_reversal": f"MathMax(f.upper_wick,f.lower_wick)/MathMax(f.body_price,_Point) >= {float(rules.get('entry', {}).get('wick_ratio_min') or 1.5):.8f}",
    }.get(family, "false")
    expressions.append(family_expr)
    return " &&\n      ".join(f"({expr})" for expr in expressions if expr != "true") or "true"


def direction_code(rules: dict[str, Any]) -> str:
    rule = str(rules.get("entry", {}).get("direction_rule") or "current_direction")
    return {
        "current_direction": "return f.direction;",
        "alignment_direction": "return SignInt(f.alignment_score);",
        "trend_direction": "return SignDouble(f.trend_12_atr);",
        "reverse_current": "return -f.direction;",
        "wick_reversal": "if(f.lower_wick > f.upper_wick) return 1; if(f.upper_wick > f.lower_wick) return -1; return 0;",
    }.get(rule, "return 0;")


def _magic(rule_hash: str) -> int:
    return 30000000 + (int(rule_hash[:8], 16) % 60000000)


MQL_TEMPLATE = r'''//+------------------------------------------------------------------+
//| __FILE_NAME__
//| Generated by EVE Evolution Discovery Lab from frozen rules.
//| Strategy: __STRATEGY_NAME__
//| Strategy code: __STRATEGY_CODE__
//| Rules SHA-256: __RULE_HASH__
//| STATUS: METAEDITOR COMPILE + DEMO FORWARD TEST ONLY
//+------------------------------------------------------------------+
#property copyright "EVE Evolution Discovery Lab"
#property version   "1.00"
#property strict
#property description "Autonomously composed, evolved and chronologically validated EVE strategy"

#include <Trade/Trade.mqh>

input bool   InpEnableTrading              = false; // Safety lock: demo only
input bool   InpUseFixedLot                = false;
input double InpFixedLot                   = 0.01;
input double InpRiskPercent                = __RISK_PERCENT__;
input double InpMaxDailyLossPercent        = __DAILY_LOSS__;
input int    InpMaxSpreadPoints            = __MAX_SPREAD__;
input int    InpSlippagePoints             = 20;
input bool   InpUseAutoBrokerUtcOffset     = true;
input int    InpManualBrokerUtcOffsetHours = 0;
input bool   InpAllowLong                  = true;
input bool   InpAllowShort                 = true;
input bool   InpShowStatusPanel            = true;
input bool   InpVerboseLogging             = true;

const string EVE_STRATEGY_CODE = "__STRATEGY_CODE__";
const string EVE_STRATEGY_NAME = "__STRATEGY_NAME__";
const string EVE_RULE_HASH     = "__RULE_HASH__";
const long   EVE_MAGIC         = __MAGIC__;
const double EVE_STOP_ATR      = __STOP_ATR__;
const double EVE_TARGET_ATR    = __TARGET_ATR__;
const int    EVE_MAX_HOLD_MIN  = __MAX_HOLD__;
const int    EVE_COOLDOWN_MIN  = __COOLDOWN__;

CTrade trade;
datetime last_m5_bar=0;
datetime last_entry_time=0;
string current_status="Starting";

struct FeatureSet
{
   int weekday;
   int month;
   int hour_utc;
   string session;
   string regime;
   int direction;
   int alignment_score;
   double atr_14;
   double trend_12_atr;
   double trend_48_atr;
   string trend_12_band;
   string trend_48_band;
   double compression_ratio;
   string compression_band;
   double return_1_pct;
   double return_3_pct;
   double close_location;
   double body_price;
   double upper_wick;
   double lower_wick;
};

int SignDouble(const double value){ if(value>1e-12) return 1; if(value<-1e-12) return -1; return 0; }
int SignInt(const int value){ if(value>0) return 1; if(value<0) return -1; return 0; }
string TrendBand(const double value){ if(value>=0.18) return "up"; if(value<=-0.18) return "down"; return "flat"; }
string CompressionBand(const double value){ if(value<0.72) return "compressed"; if(value>1.35) return "expanded"; return "normal"; }

bool IsLeapYear(const int year){ return ((year%4==0 && year%100!=0) || year%400==0); }
int DaysInMonth(const int year,const int month){ if(month==2) return IsLeapYear(year)?29:28; if(month==4||month==6||month==9||month==11) return 30; return 31; }
int DayOfWeekUtc(const datetime value){ MqlDateTime dt; TimeToStruct(value,dt); return dt.day_of_week; }
int LastSunday(const int year,const int month){ MqlDateTime dt; dt.year=year;dt.mon=month;dt.day=DaysInMonth(year,month);dt.hour=12;dt.min=0;dt.sec=0; datetime t=StructToTime(dt); return dt.day-DayOfWeekUtc(t); }
int NthSunday(const int year,const int month,const int nth){ MqlDateTime dt;dt.year=year;dt.mon=month;dt.day=1;dt.hour=12;dt.min=0;dt.sec=0; datetime t=StructToTime(dt); int d=DayOfWeekUtc(t); int first=d==0?1:8-d; return first+(nth-1)*7; }
bool IsLondonDstUtc(const datetime utc_time){ MqlDateTime dt;TimeToStruct(utc_time,dt); MqlDateTime a,b; a.year=dt.year;a.mon=3;a.day=LastSunday(dt.year,3);a.hour=1;a.min=0;a.sec=0; b.year=dt.year;b.mon=10;b.day=LastSunday(dt.year,10);b.hour=1;b.min=0;b.sec=0; return utc_time>=StructToTime(a)&&utc_time<StructToTime(b); }
bool IsNewYorkDstUtc(const datetime utc_time){ MqlDateTime dt;TimeToStruct(utc_time,dt); MqlDateTime a,b; a.year=dt.year;a.mon=3;a.day=NthSunday(dt.year,3,2);a.hour=7;a.min=0;a.sec=0; b.year=dt.year;b.mon=11;b.day=NthSunday(dt.year,11,1);b.hour=6;b.min=0;b.sec=0; return utc_time>=StructToTime(a)&&utc_time<StructToTime(b); }
int BrokerUtcOffsetSeconds(){ if(!InpUseAutoBrokerUtcOffset) return InpManualBrokerUtcOffsetHours*3600; datetime server=TimeTradeServer();datetime utc=TimeGMT(); if(server<=0||utc<=0) return InpManualBrokerUtcOffsetHours*3600; return (int)(server-utc); }
datetime ServerToUtc(const datetime server_time){ return server_time-BrokerUtcOffsetSeconds(); }
string SessionName(const datetime utc_time){ MqlDateTime utc;TimeToStruct(utc_time,utc); int london=(utc.hour+(IsLondonDstUtc(utc_time)?1:0))%24; int ny=(utc.hour+(IsNewYorkDstUtc(utc_time)?-4:-5)+24)%24; if(ny>=8&&ny<17) return "new_york"; if(london>=8&&london<13) return "london"; if(utc.hour>=0&&utc.hour<7) return "asia"; return "off_session"; }

bool GetRates(const ENUM_TIMEFRAMES timeframe,const int start_shift,const int count,MqlRates &rates[]){ ArraySetAsSeries(rates,true); return CopyRates(_Symbol,timeframe,start_shift,count,rates)==count; }
double LinearSlopeChronological(const double &values[],const int count){ if(count<2) return 0.0; double xm=(count-1)/2.0,ym=0.0; for(int i=0;i<count;i++) ym+=values[i];ym/=count; double n=0,d=0; for(int i=0;i<count;i++){ double dx=i-xm;n+=dx*(values[i]-ym);d+=dx*dx;} return d>0?n/d:0.0; }
int CompletedCandleDirection(const ENUM_TIMEFRAMES timeframe){ return SignDouble(iClose(_Symbol,timeframe,1)-iOpen(_Symbol,timeframe,1)); }
int CalculateAlignmentScore(){ return CompletedCandleDirection(PERIOD_M15)+CompletedCandleDirection(PERIOD_H1)+CompletedCandleDirection(PERIOD_H4)+CompletedCandleDirection(PERIOD_D1); }

bool CalculateFeatureSet(FeatureSet &f)
{
   MqlRates bars[];
   if(!GetRates(PERIOD_M5,1,70,bars)) return false;
   double tr=0.0;
   for(int i=0;i<14;i++){
      double prev=bars[i+1].close;
      tr+=MathMax(bars[i].high-bars[i].low,MathMax(MathAbs(bars[i].high-prev),MathAbs(bars[i].low-prev)));
   }
   f.atr_14=tr/14.0;
   if(f.atr_14<=0) return false;
   datetime utc_time=ServerToUtc(bars[0].time);
   MqlDateTime dt;TimeToStruct(utc_time,dt);
   f.weekday=dt.day_of_week==0?7:dt.day_of_week;
   f.month=dt.mon;
   f.hour_utc=dt.hour;
   f.session=SessionName(utc_time);
   f.direction=SignDouble(bars[0].close-bars[0].open);
   f.alignment_score=CalculateAlignmentScore();

   double r3=0,r12=0;
   for(int i=0;i<3;i++) r3+=bars[i].high-bars[i].low;
   for(int i=0;i<12;i++) r12+=bars[i].high-bars[i].low;
   double avg12=r12/12.0;
   f.compression_ratio=avg12>0?(r3/3.0)/avg12:1.0;
   f.compression_band=CompressionBand(f.compression_ratio);

   double closes12[12]; for(int i=0;i<12;i++) closes12[i]=bars[11-i].close;
   double closes48[48]; for(int i=0;i<48;i++) closes48[i]=bars[47-i].close;
   f.trend_12_atr=LinearSlopeChronological(closes12,12)/f.atr_14;
   f.trend_48_atr=LinearSlopeChronological(closes48,48)/f.atr_14;
   f.trend_12_band=TrendBand(f.trend_12_atr);
   f.trend_48_band=TrendBand(f.trend_48_atr);

   f.return_1_pct=bars[1].close!=0?((bars[0].close/bars[1].close)-1.0)*100.0:0.0;
   f.return_3_pct=bars[3].close!=0?((bars[0].close/bars[3].close)-1.0)*100.0:0.0;
   double range=bars[0].high-bars[0].low;
   f.close_location=range>0?(bars[0].close-bars[0].low)/range:0.5;
   f.body_price=MathAbs(bars[0].close-bars[0].open);
   f.upper_wick=bars[0].high-MathMax(bars[0].open,bars[0].close);
   f.lower_wick=MathMin(bars[0].open,bars[0].close)-bars[0].low;
   if(f.compression_ratio<0.72) f.regime="compression";
   else if(MathAbs(f.trend_12_atr)>=0.18) f.regime=f.trend_12_atr>0?"trend_up":"trend_down";
   else if(avg12>0 && f.atr_14>=avg12*1.25) f.regime="high_volatility";
   else f.regime="range";
   return true;
}

bool SourceConditionMatched(const FeatureSet &f)
{
   return __SOURCE_EXPRESSION__;
}

int StrategyDirection(const FeatureSet &f)
{
   __DIRECTION_CODE__
}

bool HasOurPosition(){ for(int i=PositionsTotal()-1;i>=0;i--){ ulong ticket=PositionGetTicket(i); if(ticket==0||!PositionSelectByTicket(ticket)) continue; if(PositionGetString(POSITION_SYMBOL)==_Symbol&&PositionGetInteger(POSITION_MAGIC)==EVE_MAGIC) return true;} return false; }
void SetStatus(const string value){ current_status=value; if(InpShowStatusPanel) Comment("EVE DISCOVERY BOT\n",EVE_STRATEGY_NAME,"\n",value,"\nTrading: ",InpEnableTrading?"ENABLED":"OFF (safety)","\nHash: ",StringSubstr(EVE_RULE_HASH,0,12)); }
void ManageMaximumHold(){ for(int i=PositionsTotal()-1;i>=0;i--){ ulong ticket=PositionGetTicket(i);if(ticket==0||!PositionSelectByTicket(ticket)) continue; if(PositionGetString(POSITION_SYMBOL)!=_Symbol||PositionGetInteger(POSITION_MAGIC)!=EVE_MAGIC) continue; datetime opened=(datetime)PositionGetInteger(POSITION_TIME); if(TimeCurrent()-opened>=EVE_MAX_HOLD_MIN*60){ trade.PositionClose(ticket,InpSlippagePoints);SetStatus("Time exit completed"); } } }

double ClosedProfitToday(){ MqlDateTime now;TimeToStruct(TimeCurrent(),now);now.hour=0;now.min=0;now.sec=0;datetime start=StructToTime(now);if(!HistorySelect(start,TimeCurrent())) return 0.0;double result=0.0;for(int i=0;i<HistoryDealsTotal();i++){ulong t=HistoryDealGetTicket(i);if(t==0) continue;if(HistoryDealGetString(t,DEAL_SYMBOL)!=_Symbol) continue;if((long)HistoryDealGetInteger(t,DEAL_MAGIC)!=EVE_MAGIC) continue;long entry=(long)HistoryDealGetInteger(t,DEAL_ENTRY);if(entry!=DEAL_ENTRY_OUT&&entry!=DEAL_ENTRY_OUT_BY) continue;result+=HistoryDealGetDouble(t,DEAL_PROFIT)+HistoryDealGetDouble(t,DEAL_SWAP)+HistoryDealGetDouble(t,DEAL_COMMISSION);}return result;}
bool DailyLossGuardPassed(){ if(InpMaxDailyLossPercent<=0) return true;double balance=AccountInfoDouble(ACCOUNT_BALANCE);return ClosedProfitToday()>-(balance*InpMaxDailyLossPercent/100.0); }
double NormalizeVolume(double volume){ double minLot=SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_MIN),maxLot=SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_MAX),step=SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_STEP);if(step<=0) step=minLot;volume=MathMax(minLot,MathMin(maxLot,volume));volume=MathFloor(volume/step+1e-9)*step;int digits=step<0.001?4:(step<0.01?3:2);return NormalizeDouble(volume,digits); }
double CalculateVolume(const double stopDistance){ if(InpUseFixedLot) return NormalizeVolume(InpFixedLot);double riskMoney=AccountInfoDouble(ACCOUNT_BALANCE)*InpRiskPercent/100.0;double tickSize=SymbolInfoDouble(_Symbol,SYMBOL_TRADE_TICK_SIZE);double tickValue=SymbolInfoDouble(_Symbol,SYMBOL_TRADE_TICK_VALUE_LOSS);if(tickValue<=0) tickValue=SymbolInfoDouble(_Symbol,SYMBOL_TRADE_TICK_VALUE);if(stopDistance<=0||tickSize<=0||tickValue<=0) return NormalizeVolume(InpFixedLot);return NormalizeVolume(riskMoney/((stopDistance/tickSize)*tickValue)); }
bool CooldownPassed(){ string key="EVE_DISCOVERY_LAST_"+IntegerToString((int)EVE_MAGIC)+"_"+_Symbol;if(GlobalVariableCheck(key)) last_entry_time=(datetime)GlobalVariableGet(key);return last_entry_time==0||TimeCurrent()-last_entry_time>=EVE_COOLDOWN_MIN*60; }
void SaveEntryTime(){ last_entry_time=TimeCurrent();string key="EVE_DISCOVERY_LAST_"+IntegerToString((int)EVE_MAGIC)+"_"+_Symbol;GlobalVariableSet(key,(double)last_entry_time); }
bool SpreadPassed(){ MqlTick tick;if(!SymbolInfoTick(_Symbol,tick)) return false;return InpMaxSpreadPoints<=0||(tick.ask-tick.bid)/_Point<=InpMaxSpreadPoints; }

void EvaluateNewSignal()
{
   if(!InpEnableTrading){ SetStatus("Waiting: internal trading switch is OFF"); return; }
   if(HasOurPosition()){ SetStatus("Managing open position"); return; }
   if(!CooldownPassed()){ SetStatus("Waiting: cooldown"); return; }
   if(!SpreadPassed()){ SetStatus("Waiting: spread too wide"); return; }
   if(!DailyLossGuardPassed()){ SetStatus("Stopped: daily loss guard"); return; }
   datetime source=iTime(_Symbol,PERIOD_M5,1);if(source<=0) return;
   MqlDateTime dt;TimeToStruct(ServerToUtc(source),dt);
   if(dt.min%15!=0){ SetStatus("Waiting for 15-minute research anchor"); return; }
   FeatureSet f;if(!CalculateFeatureSet(f)){ SetStatus("Waiting for enough market data"); return; }
   if(!SourceConditionMatched(f)){ SetStatus("Waiting: frozen market conditions not matched"); return; }
   int direction=StrategyDirection(f);
   if(direction>0&&!InpAllowLong){ SetStatus("BUY blocked by input"); return; }
   if(direction<0&&!InpAllowShort){ SetStatus("SELL blocked by input"); return; }
   if(direction==0){ SetStatus("Waiting: no direction signal"); return; }
   MqlTick tick;if(!SymbolInfoTick(_Symbol,tick)) return;
   double stopDistance=EVE_STOP_ATR*f.atr_14,targetDistance=EVE_TARGET_ATR*f.atr_14;
   double volume=CalculateVolume(stopDistance);if(volume<=0) return;
   int digits=(int)SymbolInfoInteger(_Symbol,SYMBOL_DIGITS);
   double price=direction>0?tick.ask:tick.bid;
   double sl=NormalizeDouble(direction>0?price-stopDistance:price+stopDistance,digits);
   double tp=NormalizeDouble(direction>0?price+targetDistance:price-targetDistance,digits);
   trade.SetExpertMagicNumber(EVE_MAGIC);trade.SetDeviationInPoints(InpSlippagePoints);trade.SetTypeFillingBySymbol(_Symbol);
   string comment=EVE_STRATEGY_CODE+" "+StringSubstr(EVE_RULE_HASH,0,8);
   bool opened=direction>0?trade.Buy(volume,_Symbol,0.0,sl,tp,comment):trade.Sell(volume,_Symbol,0.0,sl,tp,comment);
   if(opened){ SaveEntryTime();SetStatus(direction>0?"BUY opened":"SELL opened");Print(EVE_STRATEGY_CODE,": trade opened. hash=",EVE_RULE_HASH); }
   else { SetStatus("Order rejected: "+trade.ResultRetcodeDescription());Print(EVE_STRATEGY_CODE,": order failed ",trade.ResultRetcode()," ",trade.ResultRetcodeDescription()); }
}

int OnInit(){ trade.SetExpertMagicNumber(EVE_MAGIC);last_m5_bar=iTime(_Symbol,PERIOD_M5,0);SetStatus("Loaded and waiting");Print(EVE_STRATEGY_CODE,": loaded. Frozen hash=",EVE_RULE_HASH,". Trading defaults OFF.");return INIT_SUCCEEDED; }
void OnDeinit(const int reason){ Comment(""); }
void OnTick(){ ManageMaximumHold();datetime current=iTime(_Symbol,PERIOD_M5,0);if(current<=0||current==last_m5_bar) return;last_m5_bar=current;EvaluateNewSignal(); }
'''


def generate_mq5_source(frozen: dict[str, Any]) -> tuple[str, str]:
    rules = dict(frozen.get("rules") or {})
    risk = dict(rules.get("risk") or {})
    rule_hash = str(frozen.get("rule_hash") or sha256_text(canonical(rules)))
    code = str(frozen.get("strategy_code") or f"EVE-DISC-{rule_hash[:12].upper()}")
    name = str(frozen.get("name") or code)
    file_name = safe_name(f"{code}_v1_0") + ".mq5"
    replacements = {
        "__FILE_NAME__": file_name,
        "__STRATEGY_NAME__": mql_string(name),
        "__STRATEGY_CODE__": mql_string(code),
        "__RULE_HASH__": rule_hash,
        "__MAGIC__": str(_magic(rule_hash)),
        "__RISK_PERCENT__": f"{float(risk.get('risk_percent') or 0.25):.4f}",
        "__DAILY_LOSS__": f"{float(risk.get('max_daily_loss_percent') or 1.0):.4f}",
        "__MAX_SPREAD__": str(int(float(risk.get("max_spread_points") or 100))),
        "__STOP_ATR__": f"{float(risk.get('stop_atr') or 1.0):.8f}",
        "__TARGET_ATR__": f"{float(risk.get('target_atr') or 2.0):.8f}",
        "__MAX_HOLD__": str(int(float(risk.get("max_hold_minutes") or risk.get("horizon_minutes") or 60))),
        "__COOLDOWN__": str(int(float(risk.get("cooldown_minutes") or 60))),
        "__SOURCE_EXPRESSION__": source_expression(rules),
        "__DIRECTION_CODE__": direction_code(rules),
    }
    source = MQL_TEMPLATE
    for token, value in replacements.items():
        source = source.replace(token, value)
    return file_name, source


def static_validate(source: str, rule_hash: str) -> list[str]:
    required = [
        "#property strict", "int OnInit()", "void OnTick()", "InpEnableTrading              = false",
        "SourceConditionMatched", "StrategyDirection", "DailyLossGuardPassed", "ManageMaximumHold",
        "trade.Buy", "trade.Sell", rule_hash,
    ]
    issues = [f"Missing token: {token}" for token in required if token not in source]
    if source.count("{") != source.count("}"):
        issues.append("Unbalanced braces")
    if "__" in source:
        issues.append("Unresolved template token")
    return issues


def build_readme(frozen: dict[str, Any], file_name: str) -> str:
    rules = dict(frozen.get("rules") or {})
    metrics = dict(frozen.get("metrics") or {})
    locked = dict(metrics.get("locked") or {})
    recent = dict(metrics.get("recent") or {})
    return f"""EVE EVOLUTION DISCOVERY LAB — MT5 PACKAGE

Strategy: {frozen.get('name')}
Strategy code: {frozen.get('strategy_code')}
Family: {frozen.get('family')}
Rules SHA-256: {frozen.get('rule_hash')}
Generator: {GENERATOR_VERSION}

DEMO ONLY
This EA is generated from research-grade historical outcome replay. Compile it in MetaEditor and run it on an MT5 demo account before considering any further use. Trading is OFF by default.

VALIDATION SUMMARY
Locked profit factor: {locked.get('profit_factor')}
Locked expectancy: {locked.get('expectancy_r')}R
Locked trades: {locked.get('trades')}
Recent profit factor: {recent.get('profit_factor')}
Walk-forward stability: {frozen.get('stability_score')}%

INSTALL
1. Copy {file_name} into MT5 -> File -> Open Data Folder -> MQL5 -> Experts.
2. Open MetaEditor and compile the file.
3. Attach it to XAUUSD M5 on a DEMO account.
4. Review Inputs. Set InpEnableTrading=true only for demo forward testing.
5. Keep Algo Trading enabled and review Experts/Journal messages.

FROZEN RULES
{json.dumps(rules, indent=2, sort_keys=True)}

LIMITATIONS
- The discovery backtest uses EVE's completed market-state outcomes, not broker tick execution.
- Same-horizon stop/target ambiguity is resolved conservatively as a stop.
- The .mq5 still requires MetaEditor compilation and demo forward testing.
"""


def package_payload(frozen: dict[str, Any]) -> dict[str, Any]:
    file_name, source = generate_mq5_source(frozen)
    rule_hash = str(frozen.get("rule_hash"))
    issues = static_validate(source, rule_hash)
    if issues:
        raise ValueError("Generated MQL5 failed static validation: " + "; ".join(issues))

    manifest = {
        "package_format": "eve-evolution-discovery-mt5-v1",
        "generator_version": GENERATOR_VERSION,
        "created_at": datetime.now(timezone.utc).isoformat(),
        "strategy_code": frozen.get("strategy_code"),
        "strategy_name": frozen.get("name"),
        "family": frozen.get("family"),
        "rule_hash": rule_hash,
        "mq5_file": file_name,
        "trading_default": "OFF",
        "intended_use": "MetaEditor compile and MT5 demo forward test",
    }
    files: dict[str, bytes] = {
        file_name: source.encode(),
        "FROZEN_RULES.json": json.dumps(frozen.get("rules") or {}, indent=2, sort_keys=True).encode(),
        "VALIDATION_REPORT.json": json.dumps({
            "metrics": frozen.get("metrics") or {},
            "walk_forward": frozen.get("walk_forward") or {},
            "robustness": frozen.get("robustness") or {},
            "evidence": frozen.get("evidence") or {},
        }, indent=2, sort_keys=True).encode(),
        "MANIFEST.json": json.dumps(manifest, indent=2, sort_keys=True).encode(),
        "README.txt": build_readme(frozen, file_name).encode(),
    }
    checksums = {name: hashlib.sha256(content).hexdigest() for name, content in files.items()}
    files["SHA256SUMS.txt"] = ("\n".join(f"{digest}  {name}" for name, digest in sorted(checksums.items())) + "\n").encode()

    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        for name, content in files.items():
            archive.writestr(name, content)
    archive_bytes = buffer.getvalue()
    package_sha = hashlib.sha256(archive_bytes).hexdigest()
    package_key = f"package-{rule_hash[:28]}"
    return {
        "package_key": package_key,
        "strategy_name": frozen.get("name"),
        "family": frozen.get("family"),
        "version": "1.0",
        "file_name": f"{frozen.get('strategy_code')}-MT5-v1.0.zip",
        "mq5_file_name": file_name,
        "mq5_source": source,
        "package_base64": base64.b64encode(archive_bytes).decode(),
        "sha256": package_sha,
        "manifest": manifest,
        "size_bytes": len(archive_bytes),
        "status": "ready",
    }


def decode_package(row: dict[str, Any]) -> bytes:
    return base64.b64decode(str(row.get("package_base64") or ""))
