import fs from 'node:fs';
import assert from 'node:assert/strict';
const html=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8');
const js=fs.readFileSync(new URL('../app.js',import.meta.url),'utf8');
for (const label of ['Overview','Research Experiments','Evolution','MT5 Packages','Data Health']) assert.ok(html.includes(label));
for (const id of ['view-overview','view-candidates','view-evolution','view-mt5','view-data']) assert.equal((html.match(new RegExp(`id="${id}"`,'g'))||[]).length,1);
assert.ok(js.includes("api('/dashboard')"));
assert.ok(js.includes("api('/data-health')"));
assert.ok(js.includes("api('/mutations?limit=100')"));
assert.ok(html.includes('mutationList'));
assert.ok(js.includes('compactEvents'));
assert.ok(js.includes('TRADING PASSPORT'));
assert.ok(js.includes('X-Admin-Token'));
assert.ok(js.includes('/download'));
assert.ok(!html.includes('Required deployment order'));
assert.ok(js.includes('Legacy survivor detected'));
assert.ok(js.includes("p?.completeness?.complete===true"));
assert.ok(js.includes('Download remains locked until the passport is complete'));
console.log('frontend structure passed');
