create extension if not exists pgcrypto;

create table if not exists public.live_trader_state (
    symbol text primary key,
    state jsonb not null default '{}'::jsonb,
    updated_at timestamptz not null default now()
);

create table if not exists public.live_trader_opinions (
    id uuid primary key default gen_random_uuid(),
    observed_at timestamptz not null default now(),
    symbol text not null,
    price double precision not null,
    bias text not null,
    confidence double precision not null default 0,
    horizon_minutes integer not null default 60,
    setup_signature text not null default '',
    market_state jsonb not null default '{}'::jsonb,
    zones jsonb not null default '{}'::jsonb,
    trade_idea jsonb not null default '{}'::jsonb,
    opinion_text text not null,
    status text not null default 'open' check (status in ('open','resolved')),
    resolved_at timestamptz,
    resolved_price double precision,
    realised_move_pct double precision,
    direction_correct boolean,
    created_at timestamptz not null default now()
);

create index if not exists live_trader_opinions_open_idx
    on public.live_trader_opinions (status, observed_at);
create index if not exists live_trader_opinions_signature_idx
    on public.live_trader_opinions (setup_signature, status, observed_at desc);

create table if not exists public.live_trader_messages (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    role text not null check (role in ('user','assistant','system')),
    message text not null,
    symbol text not null default 'XAU/USD',
    market_context jsonb not null default '{}'::jsonb
);

create index if not exists live_trader_messages_recent_idx
    on public.live_trader_messages (created_at desc);

alter table public.live_trader_state enable row level security;
alter table public.live_trader_opinions enable row level security;
alter table public.live_trader_messages enable row level security;

revoke all on table public.live_trader_state from anon, authenticated;
revoke all on table public.live_trader_opinions from anon, authenticated;
revoke all on table public.live_trader_messages from anon, authenticated;

grant all on table public.live_trader_state to service_role;
grant all on table public.live_trader_opinions to service_role;
grant all on table public.live_trader_messages to service_role;
grant usage, select on all sequences in schema public to service_role;
