-- Development-only anomaly evidence used to seed EVE Scientist hypotheses.
-- This table must never contain validation, confirmation or final-holdout evidence.

create table if not exists public.scientist_evidence_miner (
    id bigint generated by default as identity primary key,
    scientist_version text not null,
    research_dataset text not null,
    signature text not null,
    kind text not null check (kind in ('single','pair')),
    feature_keys text[] not null default '{}',
    horizon_minutes integer not null check (horizon_minutes in (15,30,60,120,240)),
    sample_count integer not null default 0,
    baseline_count integer not null default 0,
    occurrence_rate double precision not null default 0,
    mean_return_pct double precision not null default 0,
    baseline_mean_return_pct double precision not null default 0,
    effect_pct double precision not null default 0,
    standardized_effect double precision not null default 0,
    p_value double precision not null default 1,
    q_value double precision not null default 1,
    year_stability double precision not null default 0,
    direction text not null default 'flat' check (direction in ('up','down','flat')),
    status text not null default 'screened' check (status in ('screened','signal')),
    evidence_score double precision not null default 0,
    metadata jsonb not null default '{}'::jsonb,
    updated_at timestamptz not null default now(),
    unique (scientist_version, research_dataset, signature)
);

comment on table public.scientist_evidence_miner is
'Development-only statistical anomaly memory for EVE Scientist. Validation, confirmation and final holdout are forbidden inputs.';

create index if not exists scientist_evidence_miner_signal_idx
    on public.scientist_evidence_miner (scientist_version, research_dataset, status, evidence_score desc);

create index if not exists scientist_evidence_miner_updated_idx
    on public.scientist_evidence_miner (updated_at desc);

alter table public.scientist_evidence_miner enable row level security;
revoke all on table public.scientist_evidence_miner from public, anon, authenticated;
grant select, insert, update, delete on table public.scientist_evidence_miner to service_role;
grant usage, select on sequence public.scientist_evidence_miner_id_seq to service_role;
