-- EVE Autonomous Scientist v1
-- Persistent scientific memory + live pattern state.
-- Additive only: existing Discovery Lab tables/functions are untouched.

create table if not exists public.scientist_hypotheses (
    id uuid primary key default gen_random_uuid(),
    hypothesis_key text not null unique,
    candidate_key text,
    scientist_version text not null,
    state text not null default 'observed',
    symbol text not null,
    timeframe text not null,
    hypothesis text not null,
    rules jsonb not null default '{}'::jsonb,
    feature_keys jsonb not null default '[]'::jsonb,
    development_metrics jsonb not null default '{}'::jsonb,
    development_score double precision not null default 0,
    evidence jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists idx_scientist_hypotheses_state_score
    on public.scientist_hypotheses (state, development_score desc);

create index if not exists idx_scientist_hypotheses_created
    on public.scientist_hypotheses (created_at desc);

create table if not exists public.scientist_feature_memory (
    id uuid primary key default gen_random_uuid(),
    feature_key text not null unique,
    scientist_version text not null,
    trials integer not null default 0,
    positive_trials integer not null default 0,
    score double precision not null default 0,
    mean_validation_pf double precision not null default 0,
    mean_validation_expectancy_r double precision not null default 0,
    mean_validation_trades double precision not null default 0,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists idx_scientist_feature_memory_score
    on public.scientist_feature_memory (score desc);

create table if not exists public.live_setups (
    id uuid primary key default gen_random_uuid(),
    frozen_strategy_id text not null unique,
    strategy_code text,
    name text,
    symbol text,
    timeframe text,
    status text not null default 'idle'
        check (status in ('idle', 'watching', 'armed', 'triggered')),
    direction text not null default 'none'
        check (direction in ('none', 'buy', 'sell')),
    similarity double precision not null default 0,
    matched_conditions integer not null default 0,
    total_conditions integer not null default 0,
    snapshot_time timestamptz,
    details jsonb not null default '{}'::jsonb,
    triggered_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists idx_live_setups_status_updated
    on public.live_setups (status, updated_at desc);

-- These tables are internal research memory. The Railway backend uses the
-- Discovery project's service-role credential; browsers must never access
-- them directly through the Data API.
alter table public.scientist_hypotheses enable row level security;
alter table public.scientist_feature_memory enable row level security;
alter table public.live_setups enable row level security;

revoke all on table public.scientist_hypotheses from anon, authenticated;
revoke all on table public.scientist_feature_memory from anon, authenticated;
revoke all on table public.live_setups from anon, authenticated;

grant select, insert, update, delete on table public.scientist_hypotheses to service_role;
grant select, insert, update, delete on table public.scientist_feature_memory to service_role;
grant select, insert, update, delete on table public.live_setups to service_role;

comment on table public.scientist_hypotheses is
    'Development-only hypotheses generated by the autonomous scientist. Confirmation and final holdout must never be used for hypothesis generation.';

comment on table public.scientist_feature_memory is
    'Selection-stage validation memory used to allocate future EVE research budget. Sealed confirmation/holdout results are excluded by design.';

comment on table public.live_setups is
    'Current recognition state for frozen/validated discoveries against the latest completed research market snapshot.';
