begin;

create table if not exists public.research_data_quarantine (
  id bigint generated by default as identity primary key,
  source_table text not null,
  record_key text not null,
  symbol text,
  candle_time timestamptz,
  reason text not null,
  payload jsonb not null,
  quarantined_at timestamptz not null default now(),
  unique (source_table, record_key)
);

insert into public.research_data_quarantine (source_table, record_key, symbol, candle_time, reason, payload)
select
  'source_snapshots',
  concat(symbol, '|', candle_time::text),
  symbol,
  candle_time,
  'Closed-market flat snapshot produced non-positive ATR; excluded from active research rather than inventing volatility.',
  to_jsonb(s)
from public.source_snapshots s
where symbol = 'XAU/USD'
  and candle_time = '2025-04-18T20:15:00Z'
  and coalesce(atr_14, 0) <= 0
on conflict (source_table, record_key) do nothing;

insert into public.research_data_quarantine (source_table, record_key, symbol, candle_time, reason, payload)
select
  'm5_research_snapshots',
  concat(symbol, '|', candle_time::text),
  symbol,
  candle_time,
  'Derived Every-M5 state inherited non-positive ATR from the quarantined Good Friday closed-market source snapshot.',
  to_jsonb(m)
from public.m5_research_snapshots m
where symbol = 'XAU/USD'
  and candle_time::date = date '2025-04-18'
  and coalesce(atr_14, 0) <= 0
on conflict (source_table, record_key) do nothing;

delete from public.m5_research_snapshots
where symbol = 'XAU/USD'
  and candle_time::date = date '2025-04-18'
  and coalesce(atr_14, 0) <= 0;

delete from public.source_snapshots
where symbol = 'XAU/USD'
  and candle_time = '2025-04-18T20:15:00Z'
  and coalesce(atr_14, 0) <= 0;

insert into public.system_events(level, component, message, details)
values (
  'success',
  'data_integrity',
  'Quarantined the Good Friday closed-market zero-ATR source snapshot and its derived Every-M5 states from active research.',
  jsonb_build_object(
    'repair_version', 'eve-zero-atr-quarantine-v1',
    'source_time', '2025-04-18T20:15:00Z',
    'symbol', 'XAU/USD',
    'policy', 'quarantine_not_impute',
    'reason', 'closed_market_flat_snapshot',
    'confirmation_holdout_access', 'unchanged'
  )
);

commit;
